import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { Footer } from "@/components";
import NextTopLoader from "nextjs-toploader";
import SessionWrapper from "@/components/SessionWrapper";
import AuthModal from "@/components/Auth/Auth-Modal/AuthModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextTopLoader />
        <SessionWrapper>
        <AuthModal />
          <Header />
          {children}
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
